#!/bin/bash

read -p "Enter script name: " scriptName

currentDir=$(pwd)
pathDB="$currentDir/$scriptName.sql"
userDB="root"

if [ -e $pathDB ]
then
mysql -u $userDB -p < $pathDB
else
echo "file does not exist"
fi
